# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18d9ad4f8e129a4cd3c74335329cb1f3283868dc99572cac0a29294a837d4811f1914815b525872363a8e8e3a53bd529ba8cfc49b457e7dc7c2ab3b2aec238e8

test:
  secret_key_base: 7e267e81adcef6c4d75c7d2bd9796a8a40e892d187c0d5beeccf8f6125d26168ded8d11d89cb61ad7d5e58d1eef262c6e05cc0711e66890b1af4b50f6e161124

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
