# Attraction.destroy_all
# Location.destroy_all
# Review.destroy_all
# Comment.destroy_all

location1 = Location.create!(name: "Las Vegas, NV, USA", photoUrl: "http://placehold.it/100x100")
location2 = Location.create!(name:"New York, NY, USA", photoUrl: "http://placehold.it/100x100")
location3 = Location.create!(name: "Washington, D.C., USA", photoUrl: "http://placehold.it/100x100")
location4 = Location.create!(name: "Ontario, Canada", photoUrl: "http://placehold.it/100x100")
location5 = Location.create!(name: "Boston, MA, USA", photoUrl: "http://placehold.it/100x100")
location6 = Location.create!(name: "Orlando, FL, USA", photoUrl: "http://placehold.it/100x100")
location7 = Location.create!(name: "Anaheim, CA, USA", photoUrl: "http://placehold.it/100x100")
location8 = Location.create!(name: "Beijing, China", photoUrl: "http://placehold.it/100x100")
location9 = Location.create!(name: "Istanbul, Turkey", photoUrl: "http://placehold.it/100x100")
location10 = Location.create!(name: "Tokyo, Japan", photoUrl: "http://placehold.it/100x100")
location11 = Location.create!(name: "Paris, France", photoUrl: "http://placehold.it/100x100")
location12 = Location.create!(name: "San Francisco, CA", photoUrl: "http://placehold.it/100x100")
location13 = Location.create!(name: "Marne-la-Vallee, France", photoUrl: "http://placehold.it/100x100")
location14 = Location.create!(name: "Epcot, FL, USA", photoUrl: "http://placehold.it/100x100")
location15 = Location.create!(name: "Tsim Sha Tsui, Hong Kong, China", photoUrl: "http://placehold.it/100x100")
location16 = Location.create!(name: "Seattle, WA, USA", photoUrl: "http://placehold.it/100x100")
location17 = Location.create!(name: "Mexico City, Mexico", photoUrl: "http://placehold.it/100x100")
location18 = Location.create!(name: "Tennessee", photoUrl: "http://placehold.it/100x100")
location19 = Location.create!(name: "Chicago, IL, USA", photoUrl: "http://placehold.it/100x100")
location20 = Location.create!(name: "China", photoUrl: "http://placehold.it/100x100")
location21 = Location.create!(name: "Sydney, Australia", photoUrl: "http://placehold.it/100x100")
location22 = Location.create!(name: "Ocean Park, Hong Kong, China", photoUrl: "http://placehold.it/100x100")
location23 = Location.create!(name: "Hong Kong, China", photoUrl: "http://placehold.it/100x100")
location24 = Location.create!(name: "Gyeonggi-do, South Korea", photoUrl: "http://placehold.it/100x100")
location25 = Location.create!(name: "London, United Kingdom", photoUrl: "http://placehold.it/100x100")
location26 = Location.create!(name: "Lantau Island, Hong Kong, China", photoUrl: "http://placehold.it/100x100")
location27 = Location.create!(name: "Seoul, South Korea", photoUrl: "http://placehold.it/100x100")
location28 = Location.create!(name: "New Orleans, LA, USA", photoUrl: "http://placehold.it/100x100")
location29 = Location.create!(name: "Versailles, France", photoUrl: "http://placehold.it/100x100")
location30 = Location.create!(name: "Nagoya, Japan", photoUrl: "http://placehold.it/100x100")

attraction1 = location1.attractions.create!(name: "Las Vegas Strip", address: "South Las Vegas Blvd, Las Vegas, NV, USA", photoUrl: "http://az616578.vo.msecnd.net/files/2016/05/14/635987913053039946-1946633074_vegas%20strip.jpg")
attraction2 = location2.attractions.create!(name: "Times Square", address: "Manhattan, NY 10036", photoUrl: "http://www.nycgo.com/images/venues/152/tripadvisortimessquare_taggeryanceyiv_5912__x_large.jpg")
attraction3 = location2.attractions.create!(name: "Central Park", address: "New York, NY 10024", photoUrl: "http://pateshestvenik.com/wp-content/uploads/2015/01/NYcentral-park.jpg")
attraction4 = location3.attractions.create!(name: "Union Station", address: "50 Massachusetts Ave NE, Washington, D.C.", photoUrl: "http://1.bp.blogspot.com/--J8eGlDBG0o/UJAm3Txul7I/AAAAAAAAAzk/7vFUXZ5R340/s1600/Union+Station+Main+Hall+facing+west.jpg")
attraction5 = location4.attractions.create!(name: "Niagara Falls", address: "Niagara Falls, Ontario L2G3Y9, Canada", photoUrl: "http://niagarafallsusa.org/wp-content/uploads/sites/32/2016/05/niagara-falls-new-york.jpg")
attraction6 = location2.attractions.create!(name: "Grand Central Terminal", address: "89 E 42nd St, New York, NY 10017", photoUrl: "http://www.nycgo.com/images/venues/1071/grand-central-terminal-04-alex-lopez__card.jpg")
attraction7 = location5.attractions.create!(name: "Faneuil Hall Marketplace", address: "4 South Market Building, Boston, MA 02109", photoUrl: "http://www.terragalleria.com/images/us-ne/usma45870.jpeg")
attraction8 = location6.attractions.create!(name: "DisneyWorld", address: "Walt Disney World Resort, Orlando, FL 32830", photoUrl: "https://s-media-cache-ak0.pinimg.com/736x/04/fe/20/04fe206eccec2f7cc2e0c4da2dd743b5.jpg")
attraction9 = location7.attractions.create!(name: "DisneyLand", address: "1313 Disneyland Dr, Anaheim, CA 92802", photoUrl: "http://www.camelotinn-anaheim.com/wp-content/uploads/2014/05/disneyland-magic-tour.jpg")
attraction10 = location8.attractions.create!(name: "Forbidden City", address: "4 Jingshan Front St, Dongcheng Qu, Beijing Shi, China", photoUrl: "http://assets.inhabitat.com/wp-content/blogs.dir/1/files/2013/11/The-Forbidden-City.jpg")

review1 = location1.reviews.create!(author: "Borat", title: "Greatest Country In The World", content: "Kazakhstan is the greatest country in the world!  All other countries are run by little girls!", photoUrl: "http://placehold.it/100x100")
review2 = location2.reviews.create!(author: "Jesse Pinkman", title: "Kazakhstan Beeyatch!", content: "Kazakhstan has the bluest skies!", photoUrl: "http://placehold.it/100x100")
review3 = location2.reviews.create!(author: "Orange Man", title: "Make Kazakhstan Great Again", content: "Kazakhstan did not live up to expectations, but I will make it great again!", photoUrl: "http://placehold.it/100x100")
review4 = attraction1.reviews.create!(author: "Peter Griffin", title: "Not Family-Friendly!", content: "They stared at my wife a lot, and this Meg girl kept bothering us.", photoUrl: "http://placehold.it/100x100")
review5 = attraction2.reviews.create!(author: "Chandler Bing", title: "I was going to Yemen!", content: "I was supposed to go to Yemen and ended up here!  I miss Monica...", photoUrl: "http://placehold.it/100x100")
review6 = attraction2.reviews.create!(author: "Jay-Z", title: "Empire State of Mind", content: "These streets will make you feel brand new!", photoUrl: "http://placeholder.it/100x100")

comment1 = review1.comments.create!(author: "Kazakhstan President Nazarbayev", content: "Borat is humiliating my country.")
comment2 = review2.comments.create!(author: "Heisenberg", content: "I am the one who knocks in Kazakhstan!")
comment3 = review3.comments.create!(author: "Barack Obama", content: "Kazakhstan just needs some ObamaCare.")
comment4 = review4.comments.create!(author: "Borat", content: "Kazakhstan is very safe country!")
comment5 = review5.comments.create!(author: "Janice", content: "I knew you were just running away!")
comment6 = review6.comments.create!(author: "Alicia Keys", content: "Big lights will inspire you!")
comment7 = review1.comments.create!(author: "Sacha Baron Cohen", content: "Mr. President needs to learn to take a joke!")
