Attraction.destroy_all
Location.destroy_all
Review.destroy_all
Comment.destroy_all

location1 = Location.create!(name: "Las Vegas, NV, USA", photoUrl: "https://media-cdn.tripadvisor.com/media/photo-s/0d/90/b1/d5/las-vegas-welcome-sign.jpg")
location2 = Location.create!(name:"New York, NY, USA", photoUrl: "http://usa.sae.edu/assets/Campuses/New-York/2015/New_York_City_view.jpg")
location3 = Location.create!(name: "Washington, D.C., USA", photoUrl: "http://clubs.alumni.umich.edu/sites/default/files/uploads/washington_dc.jpg")
location4 = Location.create!(name: "Ontario, Canada", photoUrl: "http://watercanada.net/wp-content/uploads/2014/05/Ontario-Water-pic-by-John-Vetterli.jpg")
location5 = Location.create!(name: "Boston, MA, USA", photoUrl: "https://s3.amazonaws.com/usmsswimages/5079/23343/3.jpg?1403625983")
location6 = Location.create!(name: "Orlando, FL, USA", photoUrl: "https://cdn.lennar.net/images/com/images/new-homes/6/52/mhi/Orlando_9.jpg?d=20150831T182457")
location7 = Location.create!(name: "Anaheim, CA, USA", photoUrl: "http://www.camelotinn-anaheim.com/wp-content/uploads/2013/09/masthead-paradise-pier.jpg")
location8 = Location.create!(name: "Beijing, China", photoUrl: "http://destinations.flysaa.com/photos/beijing2.jpg")
location9 = Location.create!(name: "Istanbul, Turkey", photoUrl: "http://assets.thestregisistanbul.com/lps/assets/u/istanbul.jpg")
location10 = Location.create!(name: "Tokyo, Japan", photoUrl: "http://www.abercrombiekent.co.uk/japan/tokyo/images/Asia-Japan-Tokyo.jpg")
location11 = Location.create!(name: "Paris, France", photoUrl: "https://media-cdn.tripadvisor.com/media/photo-s/06/e5/55/c5/champs-elysees.jpg")
location12 = Location.create!(name: "San Francisco, CA", photoUrl: "http://cdn-image.travelandleisure.com/sites/default/files/styles/1600x1000/public/1444253482/DG2015-san-francisco.jpg?itok=MdRJm2Zo")
location13 = Location.create!(name: "Marne-la-Vallee, France", photoUrl: "http://cdn-image.travelandleisure.com/sites/default/files/styles/720x450/public/201411-w-worlds-most-visited-tourist-attractions-disneyland-park-at-disneyland-paris.jpg?itok=83DQLK-F")
location14 = Location.create!(name: "Epcot, FL, USA", photoUrl: "http://travelchannel.sndimg.com/content/dam/images/travel/fullrights/2016/02/29/florida-attractions/florida-attractions-epcot-centre.jpg.rend.tccom.1280.960.jpeg")
location15 = Location.create!(name: "Tsim Sha Tsui, Hong Kong, China", photoUrl: "http://www.globaltravelmate.com/uploads/images/china/hongkong/china_hongkong_kowloon.jpg")
location16 = Location.create!(name: "Seattle, WA, USA", photoUrl: "https://media-cdn.tripadvisor.com/media/photo-s/03/9b/30/26/seattle.jpg")
location17 = Location.create!(name: "Mexico City, Mexico", photoUrl: "http://wikitravel.org/upload/en/thumb/a/a3/Mexico-city-cathedral.jpg/510px-Mexico-city-cathedral.jpg")
location18 = Location.create!(name: "Tennessee", photoUrl: "http://www.gsmnp.com/wp-content/uploads/close-up-view-of-where-are-Smoky-Mountains.jpg")
location19 = Location.create!(name: "Chicago, IL, USA", photoUrl: "http://images.huffingtonpost.com/2013-02-18-Chicago_IL_Image.jpg")
location20 = Location.create!(name: "China", photoUrl: "http://vizts.com/wp-content/uploads/2016/02/great-wall-of-china-beautifull-view.jpg")
location21 = Location.create!(name: "Sydney, Australia", photoUrl: "http://p-dtr.com/wp-content/uploads/2016/11/M3HuTY9vpQ6kc14QyFeQREqN.png")
location22 = Location.create!(name: "Ocean Park, Hong Kong, China", photoUrl: "http://vizts.com/wp-content/uploads/2016/01/Ocean-Park-Hong-Kong-beautifull-view.jpg")
location23 = Location.create!(name: "Hong Kong, China", photoUrl: "https://1zautl2oglzd2hfexu4dvlis-wpengine.netdna-ssl.com/wp-content/uploads/2015/11/iStock_000004100586_Large-e1446570429397.jpg")
location24 = Location.create!(name: "Gyeonggi-do, South Korea", photoUrl: "https://i1.wp.com/www.lowyatmalaysia.com/wp-content/uploads/2016/12/1482323812_114_9-awesome-things-to-do-in-gyeonggi-do-south-korea-that-most-tourists-do-not-know-about.jpg?resize=700%2C389")
location25 = Location.create!(name: "London, United Kingdom", photoUrl: "http://atom.mu/wp-content/uploads/2017/01/London-Expat-Explore-Xmas-2017.jpg")
location26 = Location.create!(name: "Lantau Island, Hong Kong, China", photoUrl: "http://www.potolkimaker.com/second2/images/stories/China/Hong%20Kong/Lantau%20Island%20of%20Hong%20Kong%201.jpg")
location27 = Location.create!(name: "Seoul, South Korea", photoUrl: "http://cc3dmrkorea.dothome.co.kr/wp-content/uploads/2015/07/Seoul02.jpg")
location28 = Location.create!(name: "New Orleans, LA, USA", photoUrl: "http://cdn.gearpatrol.com/wp-content/uploads/2015/02/72-new-orleans-gear-patrol-lead-full.jpg")
location29 = Location.create!(name: "Versailles, France", photoUrl: "http://imagestore1.blogger.hu/25_134841_642996_d973289f55a0b48364a5b94c1b21c796_4134f5_301.jpg")
location30 = Location.create!(name: "Nagoya, Japan", photoUrl: "https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwjf5OPYmtTSAhUFWxQKHXnpCKIQjBwIBA&url=http%3A%2F%2Fi.imgur.com%2F1eZ7I.jpg&bvm=bv.149397726,d.cGw&psig=AFQjCNGqcfGVbLKWSYVLZvmP98PRfvNgZA&ust=1489519492033960")

attraction1 = location1.attractions.create!(name: "Las Vegas Strip", address: "South Las Vegas Blvd, Las Vegas, NV, USA", photoUrl: "http://az616578.vo.msecnd.net/files/2016/05/14/635987913053039946-1946633074_vegas%20strip.jpg")
attraction2 = location2.attractions.create!(name: "Times Square", address: "Manhattan, NY 10036", photoUrl: "http://www.nycgo.com/images/venues/152/tripadvisortimessquare_taggeryanceyiv_5912__x_large.jpg")
attraction3 = location2.attractions.create!(name: "Central Park", address: "New York, NY 10024", photoUrl: "http://pateshestvenik.com/wp-content/uploads/2015/01/NYcentral-park.jpg")
attraction4 = location3.attractions.create!(name: "Union Station", address: "50 Massachusetts Ave NE, Washington, D.C.", photoUrl: "http://1.bp.blogspot.com/--J8eGlDBG0o/UJAm3Txul7I/AAAAAAAAAzk/7vFUXZ5R340/s1600/Union+Station+Main+Hall+facing+west.jpg")
attraction5 = location4.attractions.create!(name: "Niagara Falls", address: "Niagara Falls, Ontario L2G3Y9, Canada", photoUrl: "http://niagarafallsusa.org/wp-content/uploads/sites/32/2016/05/niagara-falls-new-york.jpg")
attraction6 = location2.attractions.create!(name: "Grand Central Terminal", address: "89 E 42nd St, New York, NY 10017", photoUrl: "http://www.nycgo.com/images/venues/1071/grand-central-terminal-04-alex-lopez__card.jpg")
attraction7 = location5.attractions.create!(name: "Faneuil Hall Marketplace", address: "4 South Market Building, Boston, MA 02109", photoUrl: "http://www.terragalleria.com/images/us-ne/usma45870.jpeg")
attraction8 = location6.attractions.create!(name: "DisneyWorld", address: "Walt Disney World Resort, Orlando, FL 32830", photoUrl: "https://s-media-cache-ak0.pinimg.com/736x/04/fe/20/04fe206eccec2f7cc2e0c4da2dd743b5.jpg")
attraction9 = location7.attractions.create!(name: "DisneyLand", address: "1313 Disneyland Dr, Anaheim, CA 92802", photoUrl: "http://www.camelotinn-anaheim.com/wp-content/uploads/2014/05/disneyland-magic-tour.jpg")
attraction10 = location8.attractions.create!(name: "Forbidden City", address: "4 Jingshan Front St, Dongcheng Qu, Beijing Shi, China", photoUrl: "http://assets.inhabitat.com/wp-content/blogs.dir/1/files/2013/11/The-Forbidden-City.jpg")
attraction11 = location9.attractions.create!(name: "Grand Bazaar", address: "Beyazıt Mh., 34126 Fatih/İstanbul, Turkey", photoUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Grand-Bazaar_Shop.jpg")
attraction12 = location10.attractions.create!(name: "Tokyo Disneyland", address: "1-1 Maihama, Urayasu, Chiba Prefecture 279-0031, Japan", photoUrl: "https://disneynerd.files.wordpress.com/2012/10/img_3448.jpg")
attraction13 = location11.attractions.create!(name: "Notre Dame Cathedral", address: "6 Parvis Notre-Dame - Pl. Jean-Paul II, 75004 Paris, France", photoUrl: "http://traveldigg.com/wp-content/uploads/2016/06/Notre-Dame-Cathedral-Paris.jpg")
attraction14 = location12.attractions.create!(name: "Golden Gate Park", address: "San Francisco, CA 94122", photoUrl: "https://25va3qc1hw-flywheel.netdna-ssl.com/wp-content/uploads/2011/03/Japanese-Tea-Garden.jpg")
attraction15 = location13.attractions.create!(name: "Disneyland Park", address: "77777 Marne-la-Vallée, France", photoUrl: "http://www.worldfortravel.com/wp-content/uploads/2013/09/Disney-Park-Paris-France.jpg")
attraction16 = location14.attractions.create!(name: "Epcot", address: "200 Epcot Center Dr, Orlando, FL 32821", photoUrl: "https://i.ytimg.com/vi/gqZUAx-xjLc/maxresdefault.jpg")
attraction17 = location11.attractions.create!(name: "Sacre Coeur Basilica", address: "35 Rue du Chevalier de la Barre, 75018 Paris, France", photoUrl: "https://cdn.shutterstock.com/shutterstock/videos/6850327/thumb/1.jpg")
attraction18 = location15.attractions.create!(name: "Tsim Sha Tsui Waterfront", address: "The Waterfront, Elements, Sorrento Tower 1, Elements, Sorrento Tower, 1 Austin Rd W, Tsim Sha Tsui, Hong Kong", photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Kowloon_Panorama.JPG/800px-Kowloon_Panorama.JPG")
attraction19 = location16.attractions.create!(name: "Pike Place Market", address: "1531 Western Ave, Seattle, WA 98101", photoUrl: "http://www.sayhellotoamerica.com/wp-content/uploads/2013/08/Pike-Place-Market-Seattle.png")
attraction20 = location17.attractions.create!(name: "The Zocalo", address: "Plaza de la Constitución S/N, Centro, Cuauhtémoc, 06010 Ciudad de México, CDMX, Mexico", photoUrl: "http://www.planetware.com/photos-large/MEX/zocalo-plaza-de-la-constitucion.jpg")
attraction21 = location18.attractions.create!(name: "Great Smoky Mountains National Park", address: "107 Park Headquarters Road Gatlinburg, TN 37738", photoUrl: "https://www.nps.gov/common/uploads/grid_builder/akr/crop16_9/108F72CC-1DD8-B71B-0BEA0D0A8F03E1B8.jpg?width=465&quality=90&mode=crop")
attraction22 = location19.attractions.create!(name: "Navy Pier", address: "600 E Grand Ave, Chicago, IL 60611", photoUrl: "http://enjoynewyears.com/images/venues/navy-pier-7.jpg")
attraction23 = location11.attractions.create!(name: "Musee Du Louvre", address: "75001 Paris, France", photoUrl: "http://www.goldenvipservices.com/wp-content/uploads/2014/11/Le-Louvre-Paris.jpg")
attraction24 = location20.attractions.create!(name: "Great Wall of China", address: "Huairou, China, 101405", photoUrl: "http://www.discoverbeijingtours.com/uploads/121008/1-12100Q0295Y25.jpg")
attraction25 = location2.attractions.create!(name: "South Street Seaport", address: "199 Water St, New York, NY 10038", photoUrl: "http://newyorktours.onboardtours.com/images/southstreetseaport.jpg")
attraction26 = location12.attractions.create!(name: "Pier 39", address: "Beach Street & The Embarcadero, San Francisco, CA 94133", photoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Pier_39,_SF,_CA,_jjron_26.03.2012.jpg/1200px-Pier_39,_SF,_CA,_jjron_26.03.2012.jpg")
attraction27 = location21.attractions.create!(name: "Sydney Opera House", address: "Bennelong Point, Sydney NSW 2000, Australia", photoUrl: "https://s-media-cache-ak0.pinimg.com/originals/4d/a9/75/4da975b79c74cd9600bf00c2ed6642f2.jpg")
attraction28 = location3.attractions.create!(name: "National Museum of Natural History - Smithsonian", address: "10th St. & Constitution Ave. NW, Washington, DC 20560", photoUrl: "http://static.travel.usnews.com/images/destinations/48/washington_dc_natural_history_flickr.jpg")
attraction29 = location22.attractions.create!(name: "Ocean Park", address: "Ocean Park, Hong Kong", photoUrl: "http://vizts.com/wp-content/uploads/2016/01/Ocean-Park-Hong-Kong-1.jpg")
attraction30 = location23.attractions.create!(name: "Victoria Peak", address: "The Peak, Hong Kong", photoUrl: "http://assets.fodors.com/destinations/74030/victoria-peak-and-the-victoria-peak-tram-hong-kong-china_main.jpg")
attraction31 = location3.attractions.create!(name: "National Air and Space Museum (Smithsonian)", address: "600 Independence Ave SW, Washington, DC 20560", photoUrl: "http://www.hotelchantilly.com/wp-content/uploads/2014/12/National-Air-and-Space-Museum.jpg")
attraction32 = location11.attractions.create!(name: "Eiffel Tower", address: "Champ de Mars, 5 Avenue Anatole France, 75007 Paris, France", photoUrl: "https://student.societyforscience.org/sites/student.societyforscience.org/files/main/articles/Eiffeltower_main.jpg")
attraction33 = location24.attractions.create!(name: "Everland Gyeonggi-Do", address: "199 Everland-ro, Pogog-eup, Cheoin-gu, Yongin-si, Gyeonggi-do, South Korea", photoUrl: "http://4.bp.blogspot.com/-VUbADUvKmCs/UMR6ZUp5iiI/AAAAAAAABFE/GbEo9iuimh8/s1600/EVERLAND1.jpg")
attraction34 = location25.attractions.create!(name: "British Museum", address: "Great Russell St, Bloomsbury, London WC1B 3DG, UK", photoUrl: "http://ywamheidebeek.org/wp-content/uploads/2013/09/981622_470102696400553_2049582283_o.jpg")
attraction35 = location26.attractions.create!(name: "Hong Kong Disneyland", address: "Lantau Island, Hong Kong", photoUrl: "http://tombricker.smugmug.com/Disney/Hong-Kong-Disneyland/i-R3CcrZQ/0/M/sleeping-beauty-castle-sunset-hong-kong-disneyland-M.jpg")
attraction36 = location27.attractions.create!(name: "Lotte World", address: "240 Olympic-ro, Jamsil 3(sam)-dong, Songpa-gu, Seoul, South Korea", photoUrl: "https://onedaykorea.com/wp-content/uploads/2014/09/Lotte-World-South-Korea.jpg")
attraction37 = location3.attractions.create!(name: "Lincoln Memorial", address: "2 Lincoln Memorial Cir NW, Washington, DC 20037", photoUrl: "http://www.inetours.com/DC/images/LMem/Lincoln-Memorial_2386.jpg")
attraction38 = location2.attractions.create!(name: "Metropolitan Museum of Art", address: "1000 5th Ave, New York, NY 10028", photoUrl: "https://media-cdn.tripadvisor.com/media/photo-s/04/22/1c/fc/metropolitan-museum-of.jpg")
attraction39 = location28.attractions.create!(name: "Bourbon Street", address: "Bourbon Street, New Orleans, LA, 70116", photoUrl: "https://c1.staticflickr.com/4/3758/10879253543_f5c478e678_b.jpg")
attraction40 = location29.attractions.create!(name: "Palace of Versailles", address: "Place d'Armes, 78000 Versailles, France", photoUrl: "https://cache-graphicslib.viator.com/graphicslib/thumbs674x446/2050/SITours/giverny-and-versailles-small-group-day-trip-from-paris-in-paris-43134.jpg")
attraction41 = location30.attractions.create!(name: "Nagashima Spa Island", address: "333 Nagashimacho Urayasu, 桑名市長島町 Mie Prefecture 511-1135, Japan", photoUrl: "http://www.nagashima-onsen.co.jp/image/1504071753_pool.jpg")


review1 = attraction1.reviews.create!(author: "Borat", title: "Greatest Country In The World", content: "Kazakhstan is the greatest country in the world!  All other countries are run by little girls!", photoUrl: "http://placehold.it/100x100")
review2 = attraction2.reviews.create!(author: "Jesse Pinkman", title: "Times Square Beeyatch!", content: "Kazakhstan has the bluest skies!", photoUrl: "http://placehold.it/100x100")
review3 = attraction2.reviews.create!(author: "Orange Man", title: "Make Kazakhstan Great Again", content: "Kazakhstan did not live up to expectations, but I will make it great again!", photoUrl: "http://placehold.it/100x100")
review4 = attraction3.reviews.create!(author: "Peter Griffin", title: "Not Family-Friendly!", content: "They stared at my wife a lot, and this Meg girl kept bothering us.", photoUrl: "http://placehold.it/100x100")
review5 = attraction4.reviews.create!(author: "Chandler Bing", title: "I was going to Yemen!", content: "I was supposed to go to Yemen and ended up here!  I miss Monica...", photoUrl: "http://placehold.it/100x100")
review6 = attraction5.reviews.create!(author: "Jay-Z", title: "Empire State of Mind", content: "These streets will make you feel brand new!", photoUrl: "http://placeholder.it/100x100")

comment1 = review1.comments.create!(author: "Kazakhstan President Nazarbayev", content: "Borat is humiliating my country.")
comment2 = review2.comments.create!(author: "Heisenberg", content: "I am the one who knocks in Kazakhstan!")
comment3 = review3.comments.create!(author: "Barack Obama", content: "Kazakhstan just needs some ObamaCare.")
comment4 = review4.comments.create!(author: "Borat", content: "Kazakhstan is very safe country!")
comment5 = review5.comments.create!(author: "Janice", content: "I knew you were just running away!")
comment6 = review6.comments.create!(author: "Alicia Keys", content: "Big lights will inspire you!")
comment7 = review1.comments.create!(author: "Sacha Baron Cohen", content: "Mr. President needs to learn to take a joke!")
